services:
  contactsAppDb:
    container_name: contactsAppDb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
        - "27019:27017"
    volumes:
      - contactsAppDb_vol:/data/db