name: Fly Deploy

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: fo1_0py6W7nusz68a7XBnrBFVADyuWC-1E6OwhunKTGzgUw


jobs:
  deploy:
    name: contactsapplication
    runs-on: ubuntu-latest
    steps:
      - run: flyctl deploy -a contactsapplication