name: Fly Deploy

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: fo1_0py6W7nusz68a7XBnrBFVADyuWC-1E6OwhunKTGzgUw


jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy -a contactsapplication